language: php

php:
  - 5.3

before_script:
  - pyrus install pear/PHP_CodeSniffer-1.5.3
  - phpenv rehash

script:
  - phpcs --report=full --extensions=php -p -w --standard=.build/phpcs/Joomla --ignore=extensions,.build .
