language: php
php:
 - 5.3
 #- 5.4
 #- 5.5
 #- 5.6

before_script:
 # - composer update
 # Install PHPCS to validate code standards
 - composer require squizlabs/php_codesniffer 1.5.6
 #- pear install PHP_CodeSniffer-1.5.3
 #- phpenv config-add .travis.ini
 #- phpenv rehash

script:
 - sh -c "libraries/vendor/bin/phpcs --report=full --extensions=php --ignore=extensions,.build -p --standard=.build/phpcs/Joomla ."
