language: php

php:
  - 5.3

before_script:
  - pyrus install pear/PHP_CodeSniffer-1.5.3
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash

script:
  #- phpcs --report=full --extensions=php -p -w --standard=.build/phpcs/Joomla .
  - phpcs --report=full --extensions=php -p -w --standard=.build/phpcs/Joomla plugins/
  - phpcs --report=full --extensions=php -p -w --standard=.build/phpcs/Joomla component/
